### ISSUE TITLE
[Question] Backport to 1.12.2?

### ISSUE THREAD

**Issue by Dimentive** [Darkhax-Minecraft/Better-Burning#1]
I had to create an issue here on the issue tracker since the comments on the CurseForge page were closed, but I was just wondering if there’s any chance that this wonderful mod could be backported to 1.12.2? I understand if it won’t, but it would be great if it could!

**Comment by KarlosWGeek** [comment]
I would also be interested in a backport for 1.12.2, the mod seems very good and I would like to install it in my modpack.

**Comment by Darkhax** [comment]
The mod has now been backported to 1.12.2 https://www.curseforge.com/minecraft/mc-mods/better-burning/files/2916377

**Comment by pimalel233** [comment]
@darkhax Thanks :)

**Comment by Dimentive** [comment]
@Darkhax Late reply, but thank you so much! 💙 You’re a brilliant developer!
