### ISSUE TITLE
Appears to be a crash when a mob destroys its held flint and steel

### ISSUE THREAD

**Issue by Jackiecrazy** [Darkhax-Minecraft/Better-Burning#12]
https://pastebin.com/SAU19iAy
It seems strange to me to put `player == null || !player.isCreative()` on line 164, do mobs track durability?

**Comment by Darkhax** [comment]
Thanks for the report, you're right this code is incorrect. A patch will be coming soon.

**Comment by Darkhax** [comment]
Sorry for taking so long, this has now been fixed.

https://www.curseforge.com/minecraft/mc-mods/better-burning/files/3332323
