### ISSUE TITLE
[1.12.2] Empty config file

### ISSUE THREAD

**Issue by pimalel233** [Darkhax-Minecraft/Better-Burning#2]
Hi there! Firstly, thanks for a great mod. I'm having an issue with 1.12.2 version of a mod, it generates empty config file for me. I have tried joining new world to see if it adds something, but nothing.
Attaching debug log from mc 1.12.2, forge 2847, and big trees mod (as it was my test instance, forgot to remove it). Tried to put myself in lave and use resistance potion, mod seems to be working, but can''t change it's settings.
[debug.log](https://github.com/Darkhax-Minecraft/Better-Burning/files/4418727/debug.log)
Is there something I am doing wrong?

**Comment by Darkhax** [comment]
Thanks for reporting the issue, it has now been fixed. The update will be available on CurseForge.
