### ISSUE TITLE
Having the Fire Resistance potion effect should also remove the fire animation in the player's camera

### ISSUE THREAD

**Issue by KarlosWGeek** [Darkhax-Minecraft/Better-Burning#3]
I'm not sure if this feature is already on the mod (if it is, then it's not working as intended) but even when I have fire resistance, the "player is on fire animation" still occurs. If I don't take damage from the fire, then what's the point? It just blocks my view.

By "fire animation in the player's camera" and "player is on fire animation", I mean this thing:
![image](https://user-images.githubusercontent.com/38844091/86503082-e560a080-bd80-11ea-8cb9-03fad7d9071c.png)

**Comment by Darkhax** [comment]
Thanks for the suggestion, it took me a while but this is finally in!
