### ISSUE TITLE
Flint and steel uses durability in creative when hitting mobs

### ISSUE THREAD

**Issue by COMBOhrenovke** [Darkhax-Minecraft/Better-Burning#5]
So, if you want, I could send you pics and logs, but currently in this message I wont because it is a simple issue.
Steps to reproduce:
1. fire up Minecraft
2. grab yourself flint and steel (in creative)
3. hit a mob
Voilà,  you've found yourself a bug.
Idk if this was intended or not, but it seem kinda stupid and strange to lose durability in creative when hitting a mob with flint and steel but not when hitting it with a fire aspect sword. Also, I think that you should make default durability loss in survival be 1 durability point, as 64 points is already a small number and loosing 3 dur for one hit is bad when you could have a fire aspect sword. But that is just a suggestion, I really like the mod and think that quality of life features like those from this mod should be implemented in the game. Bye!

**Comment by Darkhax** [comment]
Thanks for reporting. This issue was fixed a few versions ago however I don't remember which one specifically. The durability damage for the flint and steel has always been 1.
