### ISSUE TITLE
Crash with V-Tweaks challenger mobs?

### ISSUE THREAD

**Issue by azaquaz** [Darkhax-Minecraft/Better-Burning#6]
As far as I can tell, this crash was caused by an iron golem fighting a "pyro creeper," which is a creeper that spawns with some additional effects that I can't find on any of V-Tweaks' pages.

Crash: https://pastebin.com/eaizQkMX
V-Tweaks issue: https://github.com/oitsjustjose/V-Tweaks/issues/79#issue-793780735

**Comment by Darkhax** [comment]
Thanks for reporting this issue. I am not exactly sure how you created these conditions but it looks like something that wasn't a player attacked a pyro creeper while holding flint and steel. This issue should be resolved in the [new update](https://www.curseforge.com/minecraft/mc-mods/better-burning/files/3181436).
